# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      - name: Setup GitVersion
        run: |
          git fetch --unshallow 
          dotnet tool install -g GitVersion.Tool --version=5.6.0 
          dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml"
          echo "SemVer=$(dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml" /showvariable SemVer /verbosity Quiet)" >> $GITHUB_ENV

      - name: Version echo
        run: | 
          echo ${{ env.SemVer }}
          mkdir dist
          echo ${{ env.SemVer }} >> dist/version.txt


      - name: Set versions
        run: | 
          find . -name 'environment.prod.ts' | xargs sed -i 's/%SemVer%/${{ env.SemVer }}/g'
          cp -r projects dist
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: ${{ env.SemVer }} 
          # A file, directory or wildcard pattern that describes what to upload
          path: dist 
          
  secondary:
    runs-on: ubuntu-latest
    needs: 
      build
      
    steps:
      - run: | 
          ls dist


