# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: echo workspace
        run: echo "${{ github.workspace }}/petckjlzha.comcom" 
                  
      - name: peteca
        run: git fetch --unshallow
 
      - name: Setup GitVersion
        run: dotnet tool install -g GitVersion.Tool --version=5.6.0 

        
      - name: GitVersion
        id: SemVer
        run: |
          dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml"
          echo "SemVer=$(dotnet gitversion /output json /config "${{ github.workspace }}/GitVersion.yml" /showvariable SemVer /verbosity Quiet)" >> $GITHUB_ENV

      - name: Version echo
        run: echo ${{ env.SemVer }}

